# Generated by Django 2.0.13 on 2019-08-01 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hersteller',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('hersteller', models.CharField(blank=True, db_column='Hersteller', max_length=108, null=True)),
                ('postleitzahl', models.CharField(blank=True, db_column='Postleitzahl', max_length=9, null=True)),
                ('stadt', models.CharField(blank=True, db_column='Stadt', max_length=38, null=True)),
                ('straße_und_hausnummer', models.CharField(blank=True, db_column='Straße und Hausnummer', max_length=42, null=True)),
            ],
            options={
                'db_table': 'hersteller',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Interaktionsklassen',
            fields=[
                ('interactionclassid', models.IntegerField(db_column='INTERACTIONCLASSID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=113, null=True)),
            ],
            options={
                'db_table': 'interaktionsklassen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('arzneimittel', models.CharField(db_column='Arzneimittel', max_length=150)),
                ('markteintrittsdatum', models.DateField(blank=True, db_column='Markteintrittsdatum', null=True)),
                ('hersteller', models.CharField(blank=True, db_column='Hersteller', max_length=108, null=True)),
            ],
            options={
                'db_table': 'produkt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Interaktionen',
            fields=[
                ('interactionclassid1', models.ForeignKey(db_column='INTERACTIONCLASSID1', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='interaction_one', serialize=False, to='drugintcheck.Interaktionsklassen')),
                ('severity', models.CharField(blank=True, db_column='SEVERITY', max_length=13, null=True)),
                ('likelihood', models.CharField(blank=True, db_column='LIKELIHOOD', max_length=20, null=True)),
            ],
            options={
                'db_table': 'interaktionen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produktinteraktionsklassen',
            fields=[
                ('interactionclassid', models.ForeignKey(db_column='INTERACTIONCLASSID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='drugintcheck.Interaktionsklassen')),
            ],
            options={
                'db_table': 'produktinteraktionsklassen',
                'managed': False,
            },
        ),
    ]
